# Generated by Django 5.0.2 on 2024-02-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.TextField()),
                ('ingredients_list', models.TextField()),
                ('difficulty', models.TextField()),
            ],
        ),
    ]
