# Generated by Django 5.0.2 on 2024-03-03 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 3, 2, 22, 30, 14, 97985)),
            preserve_default=False,
        ),
    ]
